### ISSUE TITLE
Fastlane changelogs are missing for the last two releases

### ISSUE THREAD

**Issue by IzzySoft** [AChep/PocketMode#11]
For the releases with versionCode 5 and 6, the corresponding changelogs in Fastlane are missing. Could you please add them (and remember adding them on future releases)? Thanks!

**Comment by AChep** [comment]
Yea, I'll add them later 👍

**Comment by IzzySoft** [comment]
Great, thanks! For now I've improvised and faked the last one from the commit history, as you [can see here](https://apt.izzysoft.de/fdroid/index/apk/com.artemchep.pocketmode) :smile:

Oh, btw, if you want to point out your app is available there (one can use the F-Droid app to install and keep it up-to-date), you can [find a badge here](https://gitlab.com/IzzyOnDroid/repo#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it).

**Comment by AChep** [comment]
> Oh, btw, if you want to point out your app is available there (one can use the F-Droid app to install and keep it up-to-date), you can [find a badge here](https://gitlab.com/IzzyOnDroid/repo#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it).

That's great! Wanna see a build flavor that does not include analytics (to get rid of than evil non free net)?

**Comment by IzzySoft** [comment]
Oh, sure! Cannot be any surer :smile: My updater can distinguish (RegEx-) based on file names should you attach both to releases. Just let me know then so I can tell it which one to pick.

Wait: Did you say "Analytics"? Lemme check, I thought your app only had NonFreeNet and not Tracking. Right – and it got that because Google Play libraries were detected in the app (probably caused by `com.google.gms.google-services`). Oh, I see you were going to add Fabric Crashlytics (bad idea, I've heard it will be executed/terminated soon anyway) and Firebase Analytics as well. So yes, a build flavor without that would be much appreciated, so I don't need to add the `Tracking` flag as well. Thanks for offering that! As soon as you decided on the file names, please let me know and I prepare my updater accordingly.

PS: If you want some pointers on "privacy-friendly analytics libraries", I collect such information in my snippets. See e.g. my [F-Droid snippet](https://gitlab.com/snippets/1896503) for this.

**Comment by AChep** [comment]
Yep, definitely it's time to migrate to Firebase's crash reporting lib :D

Acra looks great. Gonna search for a similar thing to replace Firebase analytics. Migrating only crash reports to another tool kinda meh

**Comment by IzzySoft** [comment]
Yeah, that would still leave the tracker where it is… Should you find something suitable, I'd welcome a hint. My list is not quite overwhelming at the moment, and could need some more alternatives. Especially for privacy-friendly analytics. Self-hosted Matomo might be a way – but not everyone can self-host. Most important is the user has a choice (i.e. no data flow without the user having confirmed first – which is hard to achieve with those proprietary libs; many of them start transmitting as soon as the app starts, even before you got a chance to ask the user).

**Comment by IzzySoft** [comment]
Besides, while on it: On Play Store, you have version 1.4.4 – while the newest one available here is 1.2.2; mind updating Github releases?

**Comment by IzzySoft** [comment]
@AChep any news on where the missing releases/APKs are gone to and when they'll turn up here?

**Comment by AChep** [comment]
Didn't have much time to do it. Maybe I'll do it today if lucky.

**Comment by IzzySoft** [comment]
Thanks! Can you leave another comment here when done?

**Comment by IzzySoft** [comment]
Hm, maybe it helps if I wish you luck? :smiley: (no pressure, just a friendly reminder/heads-up)

**Comment by AChep** [comment]
Hola, 

The fastlane topic is kinda outdated now, as I got rid of it. Now all builds are being generated via the GitHub Actions and deployed to the GitHub Releases & Google Play store.

Also, I added the `oss` version of the app that does not include any analytics (although it does include Google Billing for now).

**Comment by AChep** [comment]
I hope that works too :)

**Comment by IzzySoft** [comment]
> The fastlane topic is kinda outdated now, as I got rid of it.

Ugh, that's bad news. So no way to keep description etc. up-to-date automatically [here](https://apt.izzysoft.de/fdroid/index/apk/com.artemchep.pocketmode) anymore, or show the changes for the current version directly. Are you sure? Where do those Github actions get their summary/description/screenshots etc. from now?

> Also, I added the oss version of the app that does not include any analytics

Oh, and **that's** good news, thanks! Though I did not see any analytics in the previous version – ugh, wait: my updater missed the versions since v1.2.2? Ah, OK, all others were added within the last 24h, that explains :laughing:

OK, so for now I'm disabling fetching Fastlane for your app as it's gone. I still hope you might reconsider. After all, it might be possible to have those Github actions place the per-release changelog it forwards to Google into the Fastlane structure as well – so maybe you will reconsider?

**Comment by AChep** [comment]
I can add summary/description/screenshots into a fastlane-like structure, but the changelogs are gone for the greater good. The changelogs can be obtained from the https://github.com/AChep/PocketMode/releases releases page and formed from the list of commits between the releases (at least they will do so, eventually).

**Comment by AChep** [comment]
The changelogs now should be generated similarly to this https://github.com/metcalfc/changelog-generator/releases/tag/v0.4.4

**Comment by IzzySoft** [comment]
PS: Unfortunately, the oss version uses a different package name, so it won't be counted as update but rather as a completely different app. Is that necessary? If it cannot be avoided, I'd have to remove the "old app" and add the new version as new app. Current users won't receive any update information. No way to inform them either.

**Comment by IzzySoft** [comment]
> The changelogs now should be generated similarly to this

No way to pick that up automatically for the per-release changelogs unfortunately. Well, so users would need to use the "Changelog" link to open that in a browser again. Not what they'd wish for, but well… Still, changes to the app's description won't be noticed either unless someone notifies me. Might not happen too often, though, I guess?

**Comment by AChep** [comment]
> PS: Unfortunately, the oss version uses a different package name, so it won't be counted as update but rather as a completely different app. Is that necessary? If it cannot be avoided, I'd have to remove the "old app" and add the new version as new app. Current users won't receive any update information. No way to inform them either.

Hmm, I think I'll change that so it stays the same.

**Comment by AChep** [comment]
> > The changelogs now should be generated similarly to this
> 
> No way to pick that up automatically for the per-release changelogs unfortunately. Well, so users would need to use the "Changelog" link to open that in a browser again. Not what they'd wish for, but well… Still, changes to the app's description won't be noticed either unless someone notifies me. Might not happen too often, though, I guess?

Probably closer to never than often 😜

**Comment by AChep** [comment]
Triggered a build that has no special package suffix for oss builds

**Comment by IzzySoft** [comment]
Thanks, that worked fine! Once the new tag showed up, I've triggered an update here, no more errors thrown. Changelog was gone of course, but :man_shrugging: Whenever you want something changed (description, screenshots), just let me know and I'll do it manually then (until you might decide to reestablish Fastlane :smile:)

So a big thanks again! Update will go live with the next sync tomorrow (unless you cann it urgent and have me triggering a sync as well?)
