### ISSUE TITLE
v1.4.12.0: OSS APK contains Crashlytics, Firebase

### ISSUE THREAD

**Issue by IzzySoft** [AChep/PocketMode#12]
Did something go wrong when attaching the `*oss*.apk` to the release? According to my library scanner, it comes with Crashlytics and Firebase Analytics. Same for v1.4.11.2. That's no longer FLOSS. Can you please check and fix?

**Comment by IzzySoft** [comment]
PS: Guess it's due to a spelling error in your `build.gradle` [here](https://github.com/AChep/PocketMode/blob/master/app/build.gradle#L145):

```gradle
if (!getGradle()
        .getStartParameter()
        .getTaskRequests()
        .toString()
        .contains("Opensource")
) {
    apply plugin: 'com.google.firebase.crashlytics'
    apply plugin: 'com.google.gms.google-services'
}
```

The flavor is spelled all lowercase (`opensource`), so it's never matched here and thus the two Google libs are *always* included?

**Comment by AChep** [comment]
Thanks for the report! 

> PS: Guess it's due to a spelling error in your `build.gradle` [here](https://github.com/AChep/PocketMode/blob/master/app/build.gradle#L145):
> 
> ```groovy-gradle
> if (!getGradle()
>         .getStartParameter()
>         .getTaskRequests()
>         .toString()
>         .contains("Opensource")
> ) {
>     apply plugin: 'com.google.firebase.crashlytics'
>     apply plugin: 'com.google.gms.google-services'
> }
> ```
> 
> The flavor is spelled all lowercase (`opensource`), so it's never matched here and thus the two Google libs are _always_ included?

That should not have caused it, cause the flavor name always comes in like this: `assembleOpensourceRelease`... I'll check what went wrong this evening.

**Comment by IzzySoft** [comment]
Thanks for the fast response! And yes, that Gradle piece was rather a raw guess (what a non-Android-dev like me was able to spot). Looking forward to your findings then. Best luck! :crossed_fingers:

**Comment by AChep** [comment]
Should be fixed by https://github.com/AChep/PocketMode/commit/d012e66784d190fe2fc3d213cedda1c294a51014

**Comment by IzzySoft** [comment]
Uh, semantics… I had thought the two being synonyms, but obviously gradlew took the "dependencies" out of their context then. Thanks a lot! Looking forward to the next release with interest :smiley:

**Comment by AChep** [comment]
> Uh, semantics… I had thought the two being synonyms, but obviously gradlew took the "dependencies" out of their context then. Thanks a lot! Looking forward to the next release with interest 😃

The weirdest part is that putting `dependencies {}` block into the `buildTypes {}` clojure actually works, haha :D

**Comment by IzzySoft** [comment]
Well, but not as expected, as we've learned :see_no_evil:

**Comment by IzzySoft** [comment]
Confirming success! :tada: Thanks again! As a result, I immediately removed Tracking and NonFreeDep (GMS is gone as well, as it was dragged in by Firebase only), effective with the next sync.
