### ISSUE TITLE
Billing Client in OSS build?

### ISSUE THREAD

**Issue by IzzySoft** [AChep/PocketMode#25]
With the latest release (v1.6.1.0), the OSS build contains the Google Billing Client, which means non-free dependencies. Was that intended, or an accident?

**Comment by AChep** [comment]
Definitely an accident. Probably happened because of the changes in Android plugin or something. I'll check it out today.

**Comment by AChep** [comment]
Damn, forgot to do that. Hopefully I won't forget it today...

**Comment by AChep** [comment]
Welp, it was always there :) You probably have changed something in the detection code. Nevertheless, as I promised, fixed it :P

**Comment by IzzySoft** [comment]
> You probably have changed something in the detection code.

Eh, my library definitions are constantly updated, yes. The Billing Client got its AntiFeatures updated several weeks ago – so I wonder why the alert-me only fired now… Nevertheless, it's fixed now. Thanks a lot! And while I should receive another alert-me once your new release comes without that, be welcome to ping me when it's there so I'm extra alert(ed) :smile:
