### ISSUE TITLE
OnePlus 7t not always working

### ISSUE THREAD

**Issue by GhostCodey** [AChep/PocketMode#30]
Hi I have a OnePlus 7t Android 11 Oxygen OS. I have the delay at 200ms and the proximity sensor only had the option of 5cm. I just had the accessibility service warning pop up and when I clicked it, it was still on. I reset it and it stopped registering when it was in a pocket. It's off and on. Happened early in the day, stopped for several hours, then happened just now. I am also aware there is a previous post about a OnePlus but I was encouraged to report.
![Screenshot_20210703-001925](https://user-images.githubusercontent.com/86867930/124346953-88b3e380-db96-11eb-919a-666cc08fe240.jpg)
![Screenshot_20210703-001912](https://user-images.githubusercontent.com/86867930/124346954-89e51080-db96-11eb-94a0-7f285b506169.jpg)
![Screenshot_20210703-002120](https://user-images.githubusercontent.com/86867930/124346956-8a7da700-db96-11eb-8b69-03872e52aec4.jpg)
![Screenshot_20210703-002106](https://user-images.githubusercontent.com/86867930/124346958-8b163d80-db96-11eb-8fcc-fbc2898d317f.jpg)
![Screenshot_20210703-002019](https://user-images.githubusercontent.com/86867930/124346959-8baed400-db96-11eb-83e5-b78f3e6c529c.jpg)

**Comment by AChep** [comment]
Okay, so it's always at 5cm, right?

**Comment by AChep** [comment]
Even if you cover the top part of the screen?

**Comment by AChep** [comment]
If so, can you try calibrating the sensor using the:

https://play.google.com/store/apps/details?id=com.mobiledirection.proximitysensorreset

**Comment by GhostCodey** [comment]
Its not always at 5cm. Sometimes when I cover it, it will say 0 but with
the proximity sensor reset, it's been working. I apologize for the late
reply this failed to send.

**Comment by AChep** [comment]
@GhostCodey so, using that app that I linked did help, right?

**Comment by GhostCodey** [comment]
Yes that app made it work 100% I haven't had any issues with it since.

**Comment by AChep** [comment]
That's amazing, gonna add a link to that app in the troubleshooting section. Thanks for the info!

**Comment by GhostCodey** [comment]
Yes, it does have it.
