### ISSUE TITLE
Proguard obfuscation in opensource build

### ISSUE THREAD

**Issue by IzzySoft** [AChep/PocketMode#35]
Is there a reason for the heavy obfuscation (proguard I guess) in the `opensource` build? Maybe that could be switched off for a bit more transparency?

**Comment by AChep** [comment]
I disagree with that. Proguard is not only an obfuscation tool but also an optimization tool.

**Comment by AChep** [comment]
Therefore a build with the proguard applied has a lower sheer size and also probably slightly faster.

**Comment by IzzySoft** [comment]
> I disagree with that. Proguard is not only an obfuscation tool but also an optimization tool.

I fully agree with that, and wasn't arguing minimization – au contaire! I was rather considering the obfuscation of library names in the DEX. There are many foss projects using minimize without obfuscation, so that should be possible. Would you mind considering?
