### ISSUE TITLE
ACRA configured with defaults?

### ISSUE THREAD

**Issue by IzzySoft** [AChep/PocketMode#75]
ACRA changed their former defaults of being opt-in to [sending silent reports](https://www.acra.ch/docs/Interactions) without asking the users' consent. It seems you're using their default settings. Can you please check and ensure it's opt-in? Choosing their "Dialog" variant would do that, for example. Thanks in advance!

**Comment by IzzySoft** [comment]
@AChep any chance for a short status at least? I cannot longer hold back the `Tracking` flag otherwise.

**Comment by AChep** [comment]
Gonna delete analytics on these weekends :)

**Comment by IzzySoft** [comment]
Thanks! Then I'll put up with those daily warnings my updater spits into my mailbox until then – and wait for it to "simply stop" once it has pulled the weekend's update :smiley:

**Comment by AChep** [comment]
@IzzySoft v1.10.4 does not have ACRA in it

**Comment by IzzySoft** [comment]
Cool, thanks! So starting with the next update run, I won't receive the daily warning anymore :smiley:
